name: Automated Versioning and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Bump Version and Create Release
    runs-on: ubuntu-latest

    # Required to allow the action to create tags and releases
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push Git tag
        if: ${{ !contains(github.event.head_commit.message, '[SKIP-CI]') }}
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          tag_prefix: v
          dry_run: true

          custom_release_rules: 'PATCH:patch,MINOR:minor,MAJOR:major'

      - name: Create GitHub Release
        if: ${{ !contains(github.event.head_commit.message, '[SKIP-CI]') && steps.tag_version.outputs.new_tag != '' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
